### ISSUE TITLE
Messaggio 'There isn’t anything to compare.' quando creo una Pull request

### ISSUE THREAD

**Issue by pasqualegiorgio** [Coding-Bunker/Ero-Forestiero#1]
Ciao ragazzi,
sto provando a creare una pull request del commit che ho fatto sul mio feature branch header-and-footer, ma mi dà il messaggio 'There isn't anything to compare' e non mi permette di andare avanti.
Cosa sto sbagliando? Come faccio a fare la pull request correttamente?

**Comment by ludovicobesana** [comment]
La pull request la fai direttamente da GitHub
Se lavori su un feature branch semplicemente vai a fare la pr sul branch desiderato.
Quindi mergi il tuo feature branch a develop (per esempio)
