### ISSUE TITLE
The cards in the "Some testimonials" section are not centered 

### ISSUE THREAD

**Issue by ludovicobesana** [Coding-Bunker/Ero-Forestiero#12]
#### Step by step
 1- I reach the site in desktop mode through this address: http://localhost:8888/
2- I reach "Some testimonials" section

#### Expected Result
I expect to see "Some testimonials" section centered 

#### Current Result 
The cards in the "Some testimonials" section are not centered 

<img width="1332" alt="bug" src="https://user-images.githubusercontent.com/35035423/114324997-ea335b80-9b2d-11eb-934f-e0cddad41066.png">

**Comment by andrea-artuso** [comment]
I've just fixed this issue, the code is in feature/FIX-HOMEPAGE branch.
