### ISSUE TITLE
The "Subscribe" button in the "Some testimonials" section has a different style than the other buttons

### ISSUE THREAD

**Issue by ludovicobesana** [Coding-Bunker/Ero-Forestiero#13]
#### Step by step
 1- I reach the site in desktop mode through this address: http://localhost:8888/
2- I reach "Some testimonials" section

#### Expected Result
I expect to see  "Subscription" button style coherent with others styles

#### Current Result 
The "Subscribe" button in the "Some testimonials" section has a different style than the other buttons

<img width="1389" alt="bug" src="https://user-images.githubusercontent.com/35035423/114325042-37afc880-9b2e-11eb-9f6c-36912b097434.png">

![bug-1](https://user-images.githubusercontent.com/35035423/114325062-5ada7800-9b2e-11eb-8627-df6e5bb8d0f3.png)

**Comment by andrea-artuso** [comment]
I've just fixed this issue, the code is in feature/FIX-HOMEPAGE branch.
