### ISSUE TITLE
Social icons misaligned with respect to their container

### ISSUE THREAD

**Issue by ludovicobesana** [Coding-Bunker/Ero-Forestiero#15]
#### Step by step
 1- I reach the site in desktop mode through this address: http://localhost:8888/
2- I reach footer section

#### Expected Result
I expect to see social icons aligned to their container 

#### Current Result 
Social icons misaligned with respect to their container 

<img width="525" alt="bug" src="https://user-images.githubusercontent.com/35035423/114325237-595d7f80-9b2f-11eb-8531-9596fa847362.png">

**Comment by andrea-artuso** [comment]
I fixed this issue, the code is pushed on feature/FIX-HOMEPAGE branch
