### ISSUE TITLE
The "Some testimonials" and "Covid" sections are not responsive and create an overflow in mobile mode

### ISSUE THREAD

**Issue by ludovicobesana** [Coding-Bunker/Ero-Forestiero#16]
#### Step by step
 1- I reach the site in mobile mode through this address: http://localhost:8888/
2- I reach "Some testimonials" section
3- I reach "Covid" section

#### Expected Result
I expect to see all responsive sections

#### Current Result 
The "Some testimonials" and "Covid" sections are not responsive and create an overflow in mobile mode

https://user-images.githubusercontent.com/35035423/114325266-7abe6b80-9b2f-11eb-9e35-5a97c7b8951f.mp4

**Comment by andrea-artuso** [comment]
I've just fixed this issue, the code is in feature/FIX-HOMEPAGE branch.
