### ISSUE TITLE
Trying to browse the other pages, I display page 404

### ISSUE THREAD

**Issue by ludovicobesana** [Coding-Bunker/Ero-Forestiero#17]
#### Step by step
 1- I reach the site in desktop mode through this address: http://localhost:8888/
2- I click "Chi siamo" in the navbar menu

#### Expected Result
I expect to reach "Chi siamo" page

#### Current Result 
Trying to browse the other pages, I display page 404

https://user-images.githubusercontent.com/35035423/114325378-1ea81700-9b30-11eb-80a1-c4a73a76ba22.mp4

**Comment by andrea-artuso** [comment]
I tried on my local machine, I get the 404 error page only when I try to reach "Chi siamo" page. Going inside wp-admin/pages I discovered that chi-siamo page isn't existing but other pages are. I think WordPress save new pages created on the local DB created in phpMyAdmin, so it show only pages in the local db not all pages created.
To fix this problem you have to add a page called "chi-siamo" and the problem will be fixed.

**Comment by ludovicobesana** [comment]
Great, let's write it in the documentation then! @andrea-artuso
